// A portable report has no remote scripts, fonts or source-image URLs.
const escape = (s) => String(s).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderGrassReport(bundle, images) {
  const payload = JSON.stringify({ bundle, images }).replace(/</g, "\\u003c");
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Verge Studio · evidence ${escape(bundle.runId)}</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#151517;color:#dedee4;font:13px system-ui,sans-serif}main{max-width:1400px;margin:auto;padding:20px}h1{font-size:22px;margin:0 0 6px}h2{font-size:15px}p{line-height:1.5}small,.dim{color:#aaaab4}.mono,td{font-variant-numeric:tabular-nums}button,select,input{font:inherit;background:#252528;color:inherit;border:1px solid #515158;border-radius:3px;padding:7px;max-width:100%}button{cursor:pointer}button:disabled{opacity:.45}button:focus-visible,a:focus-visible{outline:2px solid #ddd}a{color:inherit}header,.card{border:1px solid #393940;padding:14px;margin-bottom:12px;background:#1b1b1e}.row{display:flex;flex-wrap:wrap;gap:10px;align-items:center}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:10px}.metrics b{display:block;font-size:23px}.views{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.views canvas{width:100%;max-height:460px;object-fit:contain;background:#111113;border:1px solid #444}.views h2{margin:6px 0}#frames{display:flex;gap:4px;overflow:auto;padding:8px 0}#frames button{flex:none}table{width:100%;border-collapse:collapse;text-align:left;font-size:12px}th,td{padding:7px;border-bottom:1px solid #333}th{position:sticky;top:0;background:#232326}tr[data-cell]{cursor:pointer}tr.active{background:#39393e}.table{max-height:280px;overflow:auto}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:11px}.warning{border-left:3px solid #ccc;padding-left:10px}.checked{font-weight:bold;border:2px solid #ddd}label{display:inline-flex;gap:6px;align-items:center}.wide{flex:1;min-width:150px}@media(max-width:700px){main{padding:10px}.views{grid-template-columns:1fr}.views canvas{max-height:350px}}
</style><main>
<header><h1>Verge Studio · height and evidence</h1><div class="mono">${escape(bundle.runId)}</div><p class="warning"><b>Not validated for operational decisions.</b> Visual review does not establish physical accuracy. The band follows the estimated camera path; local ground and actual area coverage remain unknown.</p><div class="row"><button id="json">Save evidence JSON</button><button id="html">Save complete report</button><span class="dim">Temporary until saved · local CPU processing</span></div></header>
<section class="card metrics" id="metrics"></section>
<section class="card"><div class="row"><h2>Inspect the whole video</h2><label>Frame <select id="frame"></select></label><button id="prev">Previous</button><button id="next">Next</button><button id="all">All retained pixels</button></div><div id="frames"></div><div id="frameInfo"></div><div class="views"><div><h2>Original image</h2><canvas id="original"></canvas></div><div><h2>Automatic mask · white</h2><canvas id="mask"></canvas></div><div><h2>Retained pixels · white</h2><canvas id="used"></canvas></div></div><p class="dim">The original image also shows what the mask missed. Retained pixels passed the depth and band filters. Missing pixels do not mean short grass. The dashed line projects the assumed camera-path reference onto the ground; it is not an observed edge and is not occlusion-tested.</p></section>
<section class="card"><div class="row"><h2>Half-metre cells</h2><label>Sort <select id="sort"><option value="disagreement">Largest disagreement</option><option value="height">Tallest vegetation</option><option value="support">Lowest support</option></select></label></div><div id="cellInfo"></div><div class="table"><table><thead><tr><th>Cell</th><th>E50 cm</th><th>E95 cm</th><th>Ground cm</th><th>H95 cm</th><th>Frames</th><th>Samples</th><th>Spread cm</th><th>Result</th></tr></thead><tbody id="cells"></tbody></table></div><p class="dim">E50 and E95 are the default reading: percentiles of vegetation height above <em>each cell's own ground</em>, which is what a tape measures. Ground is where that datum sits above the fitted plane &mdash; a raised bed, bank or shoulder crown. H95 is the same 95th percentile measured from the fitted plane instead, kept so the difference stays visible. Spread is the H95 range between frames, not a calibrated error interval.</p></section>
<section class="card"><h2>Visual review</h2><div class="row"><label><input type="checkbox" id="grassCheck">Correct grass and band</label><label><input type="checkbox" id="heightCheck">Plausible height pattern</label><label><input type="checkbox" id="coverageCheck">Coverage limitations understood</label></div><div class="row"><input id="reviewer" placeholder="Reviewer name"><input id="note" class="wide" placeholder="Note (required to reject)"><button id="accept">Accept visually</button><button id="reject">Reject</button></div><p id="reviewState"></p></section>
<section class="card"><h2>Limitations, ground reference and provenance</h2><details open><summary>Quality and operational blockers</summary><pre id="quality"></pre></details><details><summary>Ground and band used</summary><pre id="ground"></pre></details><details><summary>Comparison with human masks</summary><pre id="comparison"></pre></details><details><summary>Data identity and parameters</summary><pre id="identity"></pre></details></section>
</main><script id="evidence" type="application/json">${payload}</script><script>(${reportApp.toString()})();</script></html>`;
}

function reportApp() {
  const { bundle: b, images } = JSON.parse(document.getElementById("evidence").textContent);
  const $ = (id) => document.getElementById(id);
  const cm = (v) => v == null ? '—' : (v * 100).toFixed(1);
  const status = { segmented: 'mask generated', 'no-grass-detected': 'no grass detected · inspect', failed: 'failed', measured: 'measured', 'insufficient-support': 'insufficient support' };
  let current = 0, selected = null, drawGeneration = 0;
  const q = b.quality;
  for (const id of ['metrics','frame','frames']) $(id).replaceChildren();
  const metric = (label, value) => { const d=document.createElement('div'); const strong=document.createElement('b');strong.textContent=value;d.append(strong,document.createTextNode(label));$('metrics').append(d); };
  metric('frames processed / total', `${q.frames.processed}/${q.frames.total}`);metric('measured cells',q.measuredCells);metric('cells with insufficient support',q.abstainedCells);metric('frames with no grass detected',q.frames.empty);metric('coverage of observed cells',`${(q.observedCellCoverage*100).toFixed(1)}%`);metric('coverage of intended area','Unknown');metric('total local time',`${(b.timing.totalMs/1000).toFixed(1)} s`);
  $('quality').textContent=JSON.stringify(q,null,2);$('ground').textContent=JSON.stringify({ground:b.ground,corridor:b.corridor,scale:b.scale},null,2);$('comparison').textContent=JSON.stringify(b.comparison,null,2);$('identity').textContent=JSON.stringify({rodovia:b.rodovia,sentido:b.sentido,km:b.km,capturado_em:b.capturado_em,contentSha256:b.contentSha256,...b.reproducibility},null,2);
  b.frames.forEach((f,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`${f.canonicalFrame} · ${status[f.status]}`;$('frame').append(option);const button=document.createElement('button');button.textContent=`${f.canonicalFrame}${f.status==='segmented'?'':' !'}`;button.title=status[f.status];button.onclick=()=>showFrame(i);$('frames').append(button);});
  const paintRuns=(ctx,runs,width,height,colour)=>{ctx.fillStyle=colour;const sx=ctx.canvas.width/width,sy=ctx.canvas.height/height;for(let j=0;j<runs.length;j+=2){let p=runs[j],end=p+runs[j+1];while(p<end){const row=Math.floor(p/width),x=p%width,n=Math.min(end-p,width-x);ctx.fillRect(x*sx,row*sy,n*sx,sy);p+=n;}}};
  async function showFrame(i) {
    const mine=++drawGeneration;current=Math.max(0,Math.min(b.frames.length-1,i));$('frame').value=current;const f=b.frames[current];
    $('frameInfo').textContent=`Frame ${f.canonicalFrame} · ${status[f.status]} · ${f.mask?.width??0}×${f.mask?.height??0} · ${f.semantic?.counts.kept??0} mask pixels · ${f.retainedPixels??0} retained pixels${f.error?' · '+f.error:''}`;
    [...$('frames').children].forEach((e,j)=>e.classList.toggle('checked',j===current));
    const image=new Image();image.src=images[current];await image.decode();if(mine!==drawGeneration)return;
    for(const id of ['original','mask','used']){const canvas=$(id);canvas.width=image.width;canvas.height=image.height;canvas.getContext('2d').drawImage(image,0,0);}
    if(f.mask)paintRuns($('mask').getContext('2d'),f.mask.runs,f.mask.width,f.mask.height,'rgba(255,255,255,.45)');
    const ctx=$('used').getContext('2d');ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.setLineDash([6,5]);for(const line of f.referenceLines??[]){ctx.beginPath();ctx.moveTo(line[0][0]*ctx.canvas.width,line[0][1]*ctx.canvas.height);ctx.lineTo(line[1][0]*ctx.canvas.width,line[1][1]*ctx.canvas.height);ctx.stroke();}ctx.setLineDash([]);for(const c of selected?[selected]:b.cells){const p=c.pixels.find((x)=>x.frameIndex===f.frameIndex);if(p)paintRuns(ctx,p.runs,f.depthWidth,f.depthHeight,'rgba(255,255,255,.85)');}
  }
  function selectCell(c){selected=c;const votes=c.frameVotes??[];$('cellInfo').textContent=`Cell ${c.key} · ${c.coordinate.alongRoadM.toFixed(2)} m along · ${c.coordinate.distanceFromRoadM.toFixed(2)} m out · ${c.reason??status[c.status]} · ground ${cm(c.localGroundM)} cm above the plane, ${c.groundContactVoxels??0} voxels touching it · H95 per frame: ${votes.map(v=>`${b.frames[v.frameIndex]?.canonicalFrame}: ${cm(v.h95M)} cm (${v.sampleCount} samples)`).join('; ')}`;const first=c.evidenceFrameIndices[0];if(first!=null)showFrame(first);else showFrame(current);rows();}
  function rows(){const mode=$('sort').value;const cells=[...b.cells].sort((a,c)=>mode==='height'?(c.extent95M??-1)-(a.extent95M??-1):mode==='support'?a.frameCount-c.frameCount:(c.h95SpreadM??-1)-(a.h95SpreadM??-1));$('cells').replaceChildren();for(const c of cells){const tr=document.createElement('tr');tr.dataset.cell=c.key;tr.tabIndex=0;tr.classList.toggle('active',c===selected);for(const value of [c.key,cm(c.extent50M),cm(c.extent95M),cm(c.localGroundM),cm(c.h95M),c.frameCount,c.sampleCount,cm(c.h95SpreadM),c.reason??status[c.status]]){const td=document.createElement('td');td.textContent=value;tr.append(td);}tr.onclick=()=>selectCell(c);tr.onkeydown=e=>{if(e.key==='Enter')selectCell(c)};$('cells').append(tr);}}
  const save=(name,text,type)=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
  $('json').onclick=()=>save(`${b.runId}-quality.json`,JSON.stringify(b,null,2),'application/json');
  $('html').onclick=()=>{$('evidence').textContent=JSON.stringify({bundle:b,images}).replace(/</g,String.fromCharCode(92)+'u003c');save(`${b.runId}-quality.html`,'<!doctype html>'+document.documentElement.outerHTML,'text/html')};
  const review=(decision)=>{if(!b.assessment){$('reviewState').textContent='No measurement to review.';return;}const checks={correctGrassAndBand:$('grassCheck').checked,plausibleHeightPattern:$('heightCheck').checked,coverageUnderstood:$('coverageCheck').checked};const reviewerId=$('reviewer').value.trim(),note=$('note').value.trim();if(!reviewerId||(decision==='accepted'&&!Object.values(checks).every(Boolean))||(decision==='rejected'&&!note)){$('reviewState').textContent='Name the reviewer and confirm all three checks to accept; give a reason to reject.';return;}b.assessment.review={status:decision,checks,reviewerId,reviewedAt:new Date().toISOString(),note:note||null};$('reviewState').textContent=`Review: ${decision==='accepted'?'visually accepted':'rejected'} · height remains unvalidated. Save to retain.`;};
  $('reviewState').textContent=`Review: ${b.assessment?.review.status??'unavailable'} · height unvalidated`;
  $('accept').onclick=()=>review('accepted');$('reject').onclick=()=>review('rejected');$('frame').onchange=()=>showFrame(Number($('frame').value));$('prev').onclick=()=>showFrame(current-1);$('next').onclick=()=>showFrame(current+1);$('sort').onchange=rows;$('all').onclick=()=>{selected=null;$('cellInfo').textContent='All retained pixels on this frame';rows();showFrame(current)};
  rows();showFrame(0);
}
